#!/usr/bin/php
<?php

$lib_path = dirname(__FILE__).'/vendor/interconnectit/search-replace-db/';
$class_file = 'srdb.class.php';
$cli_file = 'srdb.cli.php';

$cli = file_get_contents($lib_path . $cli_file);
$class = file_get_contents($lib_path . $class_file);

// drop require in cli
$regex = '/^require_once.*'. str_replace('.', '\.', $class_file) .'.*$/m';
$cli = preg_replace($regex, '// -- inserted at the end of this file --', $cli);

// drop php open tag
$class = preg_replace('/^\<\?php.*$/m', '', $class);
$out = $cli ."\n\n". $class;

// update script
$script_file = dirname(__FILE__).'/sync-db';
$script = file_get_contents($script_file);

$search = '/^(\s*\/\/SRDB-DATA #).*(\n\s*)return .*$/m';
$replace = '\1 Updated on '. date('Y-m-d H:i:s') .'\2return \''. base64_encode($out). '\';';
$script = preg_replace($search, $replace, $script);

file_put_contents($script_file, $script);